# All SpaceVim option below [option] section
[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  colorscheme = "one"
  background = "dark"

  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = true

  statusline_separator = "arrow"
  statusline_inactive_separator = "arrow"

  enable_tabline_filetype_icon = false
  enable_os_fileformat_icon = false

  enable_statusline_display_mode = false
  statusline_unicode_symbols = false

  error_symbol = "x"
  warning_symbol = "w"
  info_symbol = "i"

  buffer_index_type = 4
  windows_index_type = 3

[[custom_plugins]]
  name = "rakr/vim-one"

[[layers]]
  name = "autocomplete"
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = "fzf"

[[layers]]
  name = "git"

[[layers]]
  name = "github"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#ruby"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#lisp"

[[layers]]
  name = "shell"
  enable = false
